changes in github_action.yml

diff --git a/.github/workflows/github_action.yml b/.github/workflows/github_action.yml
--- a/.github/workflows/github_action.yml
+++ b/.github/workflows/github_action.yml
@@ -25,9 +25,14 @@ jobs:
           pythom -m pip install --upgrade pip
           pip install black
           pip install pylint
+          pip install pylint-exit
 
       # Runs a set of commands using the runners shell
       - name: Run a multi-line script
         run: |
-          pylint * --max-line-length=80
+          pylint * --max-line-length=80 || pylint-exit $?
+          if [ $? -ne 0 ]; then
+            echo "An error occurred while running pylint." >&2
+            exit 1
+          fi
           black --check .
